version: "3.8"

services:

  configserver:
    image: klebermart/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - ms-bank-app-network

  account:
    image: klebermart/account:latest
    ports:
      - "8080:8080"
    networks:
      - ms-bank-app-network
    
  loan:
    image: klebermart/loan:latest
    ports:
      - "8090:8090"
    networks:
      - ms-bank-app-network
    
  card:
    image: klebermart/card:latest
    ports:
      - "9000:9000"
    networks:
      - ms-bank-app-network
    
networks:
  ms-bank-app-network: