version: "3.8"

services:

  configserver:
    image: ms-bank-app/configserver:0.0.1
    ports:
      - "8071:8071"
    networks:
      - ms-bank-app-network

  account:
    image: ms-bank-app/account:0.0.2
    ports:
      - "8080:8080"
    networks:
      - ms-bank-app-network
    
  loan:
    image: ms-bank-app/loan:0.0.2
    ports:
      - "8090:8090"
    networks:
      - ms-bank-app-network
    
  card:
    image: ms-bank-app/card:0.0.2
    ports:
      - "9000:9000"
    networks:
      - ms-bank-app-network
    
networks:
  ms-bank-app-network: