version: "3.8"

services:

  configserver:
    image: klebermart/configserver:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    ports:
      - "8071:8071"
    networks:
      - bank-app-network

  account:
    image: klebermart/account:latest
    ports:
      - "8080:8080"
    networks:
      - bank-app-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loan:
    image: klebermart/loan:latest
    ports:
      - "8090:8090"
    networks:
      - bank-app-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  card:
    image: klebermart/card:latest
    ports:
      - "9000:9000"
    networks:
      - bank-app-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  bank-app-network: