# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loan-deployment
deploymentLabel: loan

replicaCount: 1

image:
  repository: klebermart/loan
  tag: latest

containerPort: 8090

service:
  type: 
  port: 8090
  targetPort: 8090

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true